// clase8_SPA_Frontend/poc_react/poc_react/src/components/Apuesta.jsx
import "./apuesta.css";
import { useState } from "react";

export default function Apuesta(props) {
  const [contador, setContador] = useState(0);
  function aumentarContador() {
    setContador((contador) => contador + 1);
  }
  return (
    <div className="apuesta">
      <h1>{props.numero}</h1>
      <button onClick={aumentarContador}>Apostar $1</button>
      <p>
        Usted ha apostado ${contador} en el numero {props.numero}
      </p>
    </div>
  );
}

// clase8_SPA_Frontend/poc_angular/src/app/apuesta/apuesta.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-apuesta',
  standalone: true,
  imports: [],
  templateUrl: './apuesta.component.html',
  styleUrl: './apuesta.component.css',
})
export class ApuestaComponent {
  contador = 0;
  @Input() numero = 0;
  aumentarContador() {
    this.contador++;
  }
}

<div class="apuesta">
  <h1>{{ numero }}</h1>
  <button (click)="aumentarContador()">Apostar $1</button>
  <p>Usted ha apostado {{ contador }} en el numero {{ numero }}</p>
</div>
