// clase8_SPA_Frontend/poc_vue/src/components/Apuesta.vue
<script setup>
import { ref } from 'vue';

const props = defineProps(['numero'])
let contador = ref(0)
function aumentarContador() {
    contador.value++
}
</script>

<template>
    <div class="apuesta">
        <h1>{{ numero }}</h1>
        <button @click="aumentarContador">Apostar $1</button>
        <p>
            Usted ha apostado {{ contador }} en el numero {{ numero }}
        </p>
    </div>
</template>

<style scoped>
.apuesta {
    border: 2px solid black;
    margin: 2rem;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
}
</style>

// clase8_SPA_Frontend/poc_react/poc_react/src/components/Apuesta.jsx
import "./apuesta.css";
import { useState } from "react";

export default function Apuesta(props) {
  const [contador, setContador] = useState(0);
  function aumentarContador() {
    setContador((contador) => contador + 1);
  }
  return (
    <div className="apuesta">
      <h1>{props.numero}</h1>
      <button onClick={aumentarContador}>Apostar $1</button>
      <p>
        Usted ha apostado ${contador} en el numero {props.numero}
      </p>
    </div>
  );
}
